### PR TITLE
Zelle import

### PR DESCRIPTION
**Pull request by cristian-ungureanu**

### CODE REVIEW

**Comment by rodica-andronache** [comment]
@abaicus can you please check here why cypress is failing?

**Comment by abaicus** [comment]
You can usually check the logs to get an idea of why it might get stalled. Probably it timed out on loading.

https://travis-ci.com/Codeinwp/ti-onboarding/jobs/220362079#L615

**Comment by rodica-andronache** [comment]
Thanks, I've checked the logs but didn't understand what's happening :)

**Comment by rodica-andronache** [comment]
@Codeinwp/theme-dev someone can please help here? I don't understand why the release doesn't seem to work. Am I missing anything?

**Comment by selul** [comment]
the amount of `chore`s we have used in the commit description did not trigger the release. 
 
You can read more about the semantic release and how it works https://github.com/semantic-release/semantic-release but for now, the release will trigger when any of the commits will have `fix:` or `feat: ` in the commit title. 

Right now you can see in the build logs that https://travis-ci.com/Codeinwp/ti-onboarding/builds/121105521 that no commits triggered this release.

**Pull request merged**
